import { createDatabase, type SqliteOptions } from "./sqlite.js";
import { SessionRepository } from "./session-repo.js";
import { IdempotencyRepository } from "./idempotency-repo.js";
import { TranscriptLog } from "./transcript-log.js";
import { AuditLog } from "./audit-log.js";
import { ApprovalRepository } from "./approval-repo.js";
import { CostLedgerRepository } from "./cost-ledger-repo.js";
import { ApprovalEventRepository } from "./approval-event-repo.js";
import { PendingApprovalActionRepository } from "./pending-approval-action-repo.js";
import { OrchestrationRepository } from "./orchestration-repo.js";
import { TaskRepository } from "./task-repo.js";
import { TaskActivityRepository } from "./task-activity-repo.js";
import { TaskDeliverableRepository } from "./task-deliverable-repo.js";
import { TaskSubagentRepository } from "./task-subagent-repo.js";
import { RealtimeEventRepository } from "./realtime-event-repo.js";
import { CronJobRepository } from "./cron-job-repo.js";
import { IntegrationConnectionRepository } from "./integration-connection-repo.js";
import { MeshRepository } from "./mesh-repo.js";
import { MemoryContextRepository } from "./memory-context-repo.js";
import { MemoryQmdRunRepository } from "./memory-qmd-run-repo.js";
import { AgentProfileRepository } from "./agent-profile-repo.js";
import { ToolGrantRepository } from "./tool-grant-repo.js";
import { ToolAccessDecisionRepository } from "./tool-access-decision-repo.js";
import { KnowledgeRepository } from "./knowledge-repo.js";
import { CommsDeliveryRepository } from "./comms-delivery-repo.js";
import { ChatProjectRepository } from "./chat-project-repo.js";
import { ChatSessionMetaRepository } from "./chat-session-meta-repo.js";
import { ChatSessionProjectRepository } from "./chat-session-project-repo.js";
import { ChatSessionBindingRepository } from "./chat-session-binding-repo.js";
import { ChatAttachmentRepository } from "./chat-attachment-repo.js";
import { ChatSessionPrefsRepository } from "./chat-session-prefs-repo.js";
import { ChatTurnTraceRepository } from "./chat-turn-trace-repo.js";
import { ChatToolRunRepository } from "./chat-tool-run-repo.js";
import { ChatInlineApprovalRepository } from "./chat-inline-approval-repo.js";
import { ChatDelegationRunRepository } from "./chat-delegation-run-repo.js";
import { ChatDelegationStepRepository } from "./chat-delegation-step-repo.js";
import { SystemSettingsRepository } from "./system-settings-repo.js";
import { ResearchRunRepository } from "./research-run-repo.js";
import { ResearchSourceRepository } from "./research-source-repo.js";
import { PromptPackRepository } from "./prompt-pack-repo.js";
import { PromptPackRunRepository } from "./prompt-pack-run-repo.js";
import { PromptPackScoreRepository } from "./prompt-pack-score-repo.js";
import { WorkspaceRepository } from "./workspace-repo.js";

export interface StorageOptions extends SqliteOptions {
  transcriptsDir: string;
  auditDir: string;
}

export class Storage {
  public readonly db: ReturnType<typeof createDatabase>;
  public readonly sessions: SessionRepository;
  public readonly idempotency: IdempotencyRepository;
  public readonly transcripts: TranscriptLog;
  public readonly audit: AuditLog;
  public readonly approvals: ApprovalRepository;
  public readonly approvalEvents: ApprovalEventRepository;
  public readonly pendingApprovalActions: PendingApprovalActionRepository;
  public readonly costLedger: CostLedgerRepository;
  public readonly orchestration: OrchestrationRepository;
  public readonly tasks: TaskRepository;
  public readonly taskActivities: TaskActivityRepository;
  public readonly taskDeliverables: TaskDeliverableRepository;
  public readonly taskSubagents: TaskSubagentRepository;
  public readonly realtimeEvents: RealtimeEventRepository;
  public readonly cronJobs: CronJobRepository;
  public readonly integrationConnections: IntegrationConnectionRepository;
  public readonly agentProfiles: AgentProfileRepository;
  public readonly mesh: MeshRepository;
  public readonly memoryContexts: MemoryContextRepository;
  public readonly memoryQmdRuns: MemoryQmdRunRepository;
  public readonly toolGrants: ToolGrantRepository;
  public readonly toolAccessDecisions: ToolAccessDecisionRepository;
  public readonly knowledge: KnowledgeRepository;
  public readonly commsDeliveries: CommsDeliveryRepository;
  public readonly chatProjects: ChatProjectRepository;
  public readonly chatSessionMeta: ChatSessionMetaRepository;
  public readonly chatSessionProjects: ChatSessionProjectRepository;
  public readonly chatSessionBindings: ChatSessionBindingRepository;
  public readonly chatAttachments: ChatAttachmentRepository;
  public readonly chatSessionPrefs: ChatSessionPrefsRepository;
  public readonly chatTurnTraces: ChatTurnTraceRepository;
  public readonly chatToolRuns: ChatToolRunRepository;
  public readonly chatInlineApprovals: ChatInlineApprovalRepository;
  public readonly chatDelegationRuns: ChatDelegationRunRepository;
  public readonly chatDelegationSteps: ChatDelegationStepRepository;
  public readonly systemSettings: SystemSettingsRepository;
  public readonly researchRuns: ResearchRunRepository;
  public readonly researchSources: ResearchSourceRepository;
  public readonly promptPacks: PromptPackRepository;
  public readonly promptPackRuns: PromptPackRunRepository;
  public readonly promptPackScores: PromptPackScoreRepository;
  public readonly workspaces: WorkspaceRepository;

  public constructor(options: StorageOptions) {
    this.db = createDatabase({ dbPath: options.dbPath });
    this.sessions = new SessionRepository(this.db);
    this.idempotency = new IdempotencyRepository(this.db);
    this.transcripts = new TranscriptLog(options.transcriptsDir);
    this.audit = new AuditLog(options.auditDir);
    this.approvals = new ApprovalRepository(this.db);
    this.approvalEvents = new ApprovalEventRepository(this.db);
    this.pendingApprovalActions = new PendingApprovalActionRepository(this.db);
    this.costLedger = new CostLedgerRepository(this.db);
    this.orchestration = new OrchestrationRepository(this.db);
    this.tasks = new TaskRepository(this.db);
    this.taskActivities = new TaskActivityRepository(this.db);
    this.taskDeliverables = new TaskDeliverableRepository(this.db);
    this.taskSubagents = new TaskSubagentRepository(this.db);
    this.realtimeEvents = new RealtimeEventRepository(this.db);
    this.cronJobs = new CronJobRepository(this.db);
    this.integrationConnections = new IntegrationConnectionRepository(this.db);
    this.agentProfiles = new AgentProfileRepository(this.db);
    this.mesh = new MeshRepository(this.db);
    this.memoryContexts = new MemoryContextRepository(this.db);
    this.memoryQmdRuns = new MemoryQmdRunRepository(this.db);
    this.toolGrants = new ToolGrantRepository(this.db);
    this.toolAccessDecisions = new ToolAccessDecisionRepository(this.db);
    this.knowledge = new KnowledgeRepository(this.db);
    this.commsDeliveries = new CommsDeliveryRepository(this.db);
    this.chatProjects = new ChatProjectRepository(this.db);
    this.chatSessionMeta = new ChatSessionMetaRepository(this.db);
    this.chatSessionProjects = new ChatSessionProjectRepository(this.db);
    this.chatSessionBindings = new ChatSessionBindingRepository(this.db);
    this.chatAttachments = new ChatAttachmentRepository(this.db);
    this.chatSessionPrefs = new ChatSessionPrefsRepository(this.db);
    this.chatTurnTraces = new ChatTurnTraceRepository(this.db);
    this.chatToolRuns = new ChatToolRunRepository(this.db);
    this.chatInlineApprovals = new ChatInlineApprovalRepository(this.db);
    this.chatDelegationRuns = new ChatDelegationRunRepository(this.db);
    this.chatDelegationSteps = new ChatDelegationStepRepository(this.db);
    this.systemSettings = new SystemSettingsRepository(this.db);
    this.researchRuns = new ResearchRunRepository(this.db);
    this.researchSources = new ResearchSourceRepository(this.db);
    this.promptPacks = new PromptPackRepository(this.db);
    this.promptPackRuns = new PromptPackRunRepository(this.db);
    this.promptPackScores = new PromptPackScoreRepository(this.db);
    this.workspaces = new WorkspaceRepository(this.db);
  }

  public close(): void {
    this.db.close();
  }
}

export * from "./sqlite.js";
export * from "./session-repo.js";
export * from "./idempotency-repo.js";
export * from "./transcript-log.js";
export * from "./audit-log.js";
export * from "./approval-repo.js";
export * from "./approval-event-repo.js";
export * from "./pending-approval-action-repo.js";
export * from "./cost-ledger-repo.js";
export * from "./orchestration-repo.js";
export * from "./task-repo.js";
export * from "./task-activity-repo.js";
export * from "./task-deliverable-repo.js";
export * from "./task-subagent-repo.js";
export * from "./realtime-event-repo.js";
export * from "./cron-job-repo.js";
export * from "./integration-connection-repo.js";
export * from "./agent-profile-repo.js";
export * from "./mesh-repo.js";
export * from "./memory-context-repo.js";
export * from "./memory-qmd-run-repo.js";
export * from "./tool-grant-repo.js";
export * from "./tool-access-decision-repo.js";
export * from "./knowledge-repo.js";
export * from "./comms-delivery-repo.js";
export * from "./chat-project-repo.js";
export * from "./chat-session-meta-repo.js";
export * from "./chat-session-project-repo.js";
export * from "./chat-session-binding-repo.js";
export * from "./chat-attachment-repo.js";
export * from "./chat-session-prefs-repo.js";
export * from "./chat-turn-trace-repo.js";
export * from "./chat-tool-run-repo.js";
export * from "./chat-inline-approval-repo.js";
export * from "./chat-delegation-run-repo.js";
export * from "./chat-delegation-step-repo.js";
export * from "./system-settings-repo.js";
export * from "./research-run-repo.js";
export * from "./research-source-repo.js";
export * from "./prompt-pack-repo.js";
export * from "./prompt-pack-run-repo.js";
export * from "./prompt-pack-score-repo.js";
export * from "./workspace-repo.js";
export * from "./safe-json.js";
